# Cloudflare Pages configuration
name = "business-expense-tracker-frontend"
compatibility_date = "2024-01-01"

[env.production]
vars = { NODE_ENV = "production" }

[env.staging]
vars = { NODE_ENV = "staging" }

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages configuration
[[pages_build_output_dir]]
value = "dist"