name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run tests
        run: |
          cd frontend
          npm run test:run

      - name: Run linting
        run: |
          cd frontend
          npm run lint

      - name: Type check
        run: |
          cd frontend
          npm run type-check

      - name: Build application
        run: |
          cd frontend
          npm run build
        env:
          VITE_API_BASE_URL: ${{ github.ref == 'refs/heads/main' && 'https://business-expense-tracker-backend.up.railway.app/api' || 'https://business-expense-tracker-backend-staging.up.railway.app/api' }}
          VITE_APP_NAME: ${{ github.ref == 'refs/heads/main' && 'Business Expense Tracker' || 'Business Expense Tracker (Staging)' }}
          VITE_APP_VERSION: ${{ github.ref == 'refs/heads/main' && '1.0.0' || '1.0.0-staging' }}
          VITE_NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: business-expense-tracker-frontend
          directory: frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'